version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "docs"
    groups:
      github-actions:
        patterns:
          - "*"
