title: Awesome Digital Humanities
tagline: Software for humanities scholars using quantitative or computational methods.
description: A curated list of tools, resources, services, organizations, training materials, and research infrastructures supporting the Digital Humanities.
lang: en-US
url: https://dh-tech.github.io
baseurl: /awesome-digital-humanities
repository: dh-tech/awesome-digital-humanities
logo: /assets/images/dhtech-logo.svg

author:
  name: DHTech
  url: https://github.com/dh-tech

social:
  name: DHTech
  links:
    - https://github.com/dh-tech

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /android-chrome-512x512.png
